# Default values for my-app-chart.

replicaCount: 1

image:
  repository: harbor.k8s.labs.itmo.loc/public/my-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: my-app.k8s.labs.itmo.loc
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: my-app-tls
  #    hosts:
  #      - my-app.k8s.labs.itmo.loc

resources:
  limits:
    memory: 256Mi
  requests:
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

env:
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  QDRANT_HOST: "qdrant"
  QDRANT_PORT: "6333"
